// src/components/EducationMenu.tsx

import React from "react";
import styles from "../styles/sharedStyles.module.css"; // Import shared styles
import EducationCard from "./EducationCard"; // Import the new EducationCard component
import { Education } from '../types/types';

// import ConstructorUniversityImage from '../assets/Education/constructor_uni.png';
// import SITImage from '../assets/Education/sit.jpeg';
// import AITImage from '../assets/Education/ait pune.jpeg';

type EducationMenuProps = {
  onClose: () => void;
  // Optionally, you can pass the SoundCloud track or playlist URL as a prop
  // trackUrl?: string;
};

// Sample list of educations
const educations: Education[] = [
  {
    degree: "Masters of Science - Computer Science Software Engineering",
    university: "Constructor University",
    duration: "2023-2024",
    description:
      "Enrolled as a transfer student. Coursework contained several modules related to technical and non-technical software engineering aspects combined with several research modules. My Masters' thesis involved performing a survey on array database query processing steps, under the guidance of Prof. Peter Baumann.",
    // imageUrl: ConstructorUniversityImage,
  },
  {
    degree: "Masters of Science - Computer Science Software Engineering",
    university: "Schaffhausen Institute of Technology",
    duration: "2020-2022",
    description:
      "Was top 2 percent of a programming - based entrance test, enabling me to avail FULL SCHOLARSHIP. Innovative degree, combining several hi-tech modules (ML, quantum computing, cybersecurity etc) with non-technical courses (organizational behaviour, product management, change management etc). Masters' thesis involved simplifying test cases generated by AutoProof for the Eiffel programming language, under Prof. Bertrand Meyer.",
      // imageUrl: AITImage,
  },
  {
    degree: "Bachelors of Engineering - Information Technology",
    university: "Army Institute of Technology (Savitribai Phule Pune University)",
    duration: "2014-2018",
    description:
      "Engineering degree providing a well-rounded knowledge of the discipline of Computer Science.",
    // imageUrl: ConstructorUniversityImage,
  },  
  // Add more educations as needed
];

const EducationMenu: React.FC<EducationMenuProps> = ({ onClose /*, trackUrl */ }) => {
    return (
    <div className={styles.fancyContainer}>
      <div className={styles.playerContainer}>
        {/* Close Button */}
        <button onClick={onClose} className={styles.closeButton} aria-label="Close Education Menu">
          &times;
        </button>
        {/* Title Section */}
        <h2 className={styles.funkyTitle}>Education</h2>
        {/* Education List */}
        <div className={styles.EducationContainer}>
          {educations.map((education) => (
            <EducationCard education ={education} />
          ))}
        </div>
      </div>
    </div>
  );
};

// Inline styles for simplicity; consider moving to CSS or a CSS-in-JS library
// const overlayStyle: React.CSSProperties = {
//   position: "fixed",
//   top: 0,
//   left: 0,
//   width: "100vw",
//   height: "100vh",
//   backgroundColor: "rgba(0, 0, 0, 0.5)",
//   display: "flex",
//   justifyContent: "center",
//   alignItems: "center",
//   zIndex: 1000,
// };

// const playerContainerStyle: React.CSSProperties = {
//   position: "relative",
//   width: "90%",
//   maxWidth: "500px",
//   padding: "20px",
//   backgroundColor: "#fff",
//   borderRadius: "10px",
// };

// const closeButtonStyle: React.CSSProperties = {
//   position: "absolute",
//   top: "10px",
//   right: "15px",
//   background: "transparent",
//   border: "none",
//   fontSize: "1.5rem",
//   cursor: "pointer",
// };

export default EducationMenu;
